language: csharp
solution: Johnston.sln

jobs:
  include:
    - dotnet: 3.1.103
      mono: none
      script:
        - dotnet restore
        - dotnet test
    - mono: latest
      script:
        - dotnet restore
        - dotnet test
